-- Create agents table for tracking remote GPU instances

CREATE TABLE agents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider provider_type NOT NULL,
    provider_instance_id TEXT,
    hostname TEXT NOT NULL,
    status agent_status NOT NULL DEFAULT 'registering',
    gpu_info JSONB,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ,
    terminated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for finding stale/active agents
CREATE INDEX idx_agents_status_last_seen ON agents (status, last_seen_at);

-- Comment on table
COMMENT ON TABLE agents IS 'Remote GPU agent instances managed by PodPilot';
COMMENT ON COLUMN agents.id IS 'Internal UUID generated by PodPilot Hub';
COMMENT ON COLUMN agents.provider IS 'Cloud provider or platform (VastAI, Runpod, local)';
COMMENT ON COLUMN agents.provider_instance_id IS 'Provider-specific instance identifier (nullable for local agents)';
COMMENT ON COLUMN agents.last_seen_at IS 'Last heartbeat or activity timestamp';
