name: Build Agent

on:
  push:
    branches: ["master"]

# Sets permissions for the GITHUB_TOKEN to allow pushing to the GitHub Container Registry.
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and Push Agent Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/podpilot-agent
          tags: |
            type=raw,value=latest,enable=true
            type=sha,prefix=,format=short

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.agent # Use a distinct name to avoid confusion
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
